### ISSUE TITLE
Need to update License header in multiple files

### ISSUE THREAD

**Issue by asgrant** [Jasig/MapPortlet#16]

**Comment by jameswennmacher** [comment]
Thanks Aaron.  FYI if someone starts to work on this,  the command 'mvn license:format' will update the license files in all headers.  Also see other notes at https://wiki.jasig.org/display/UPC/Git+Workflow+for+Committers#GitWorkflowforCommitters-Releasingartifacts as you may run into some other minor issues since this portlet hasn't been released in a while.

**Comment by ChristianMurphy** [comment]
resolved in #17

**Comment by drewwills** [comment]
Fix applied.
